Repository neutrinoceros/idefix_cli, pull requests merged in 2023-09, with the labels that each got.

#317 BUG: fix a bug where idfx digest would generate invalid json from logs that end with an inlined warning or an error
  CHANGELOG.md
  src/idefix_cli/_commands/digest.py
  tests/data/log_crash/idefix.0.log
  tests/test_digest.py
Labels: bug

#320 DOC: avoid a FutureWarning from pandas in example script
  docs/commands.md
Labels: bug, documentation

#321 ENH: add support for parsing arbitrary files with `idfx digest`
  CHANGELOG.md
  docs/commands.md
  src/idefix_cli/_commands/digest.py
  tests/test_digest.py
Labels: enhancement

#323 BUG: fix baballe digest > file.json
  CHANGELOG.md
  src/idefix_cli/__main__.py
Labels: bug

#324 BUG: fix a bug where idfx digest would choke on files where no line is captured
  CHANGELOG.md
  src/idefix_cli/_commands/digest.py
  tests/data/OrszagTang3D/empty.log
  tests/test_digest.py
Labels: bug
